"""Stable, dependency-safe contracts published by the ERP module."""

from app.modules.erp.public_api.dto import (
    ProductCategoryCreate,
    ProductCategoryPublic,
    ProductCategoryUpdate,
    ProductCreate,
    ProductPublic,
    ProductUnitCreate,
    ProductUnitPublic,
    ProductUnitUpdate,
    ProductUpdate,
    StockBalancePublic,
    StockBalancesPublic,
    StockDocumentItemCreate,
    StockInCreate,
    StockInItemPublic,
    StockInPublic,
    StockInsPublic,
    StockLedgerPublic,
    StockLedgersPublic,
    StockOutCreate,
    StockOutItemPublic,
    StockOutPublic,
    StockOutsPublic,
    WarehouseCreate,
    WarehousePublic,
    WarehouseUpdate,
)
from app.modules.erp.public_api.events import DocumentLifecycleV1, StockChangedV1

__all__ = [
    "ProductCategoryCreate",
    "ProductCategoryPublic",
    "ProductCategoryUpdate",
    "ProductCreate",
    "ProductPublic",
    "ProductUnitCreate",
    "ProductUnitPublic",
    "ProductUnitUpdate",
    "ProductUpdate",
    "WarehouseCreate",
    "WarehousePublic",
    "WarehouseUpdate",
    "StockChangedV1",
    "DocumentLifecycleV1",
    "StockBalancePublic",
    "StockBalancesPublic",
    "StockDocumentItemCreate",
    "StockInCreate",
    "StockInItemPublic",
    "StockInPublic",
    "StockInsPublic",
    "StockLedgerPublic",
    "StockLedgersPublic",
    "StockOutCreate",
    "StockOutItemPublic",
    "StockOutPublic",
    "StockOutsPublic",
]
