from app.modules.contracts import (
    EventContract,
    LifecycleHooks,
    MigrationSpec,
    ModuleDefinition,
    ReferenceGuardSpec,
    ScheduleHandler,
)
from app.modules.erp.application.schedules import (
    cleanup_completed_command_receipts,
    run_daily_reconciliation,
)
from app.modules.erp.attachment_routes import count_file_references
from app.modules.erp.attachment_routes import router as attachment_router
from app.modules.erp.audit_routes import router as audit_router
from app.modules.erp.export_routes import router as export_router
from app.modules.erp.finance_document_routes import router as finance_document_router
from app.modules.erp.finance_routes import router as finance_router
from app.modules.erp.purchase_routes import router as purchase_router
from app.modules.erp.purchase_stock_routes import router as purchase_stock_router
from app.modules.erp.reconciliation_routes import router as reconciliation_router
from app.modules.erp.reference_guards import count_user_references
from app.modules.erp.routes import router
from app.modules.erp.sale_routes import router as sale_router
from app.modules.erp.sale_stock_routes import router as sale_stock_router
from app.modules.erp.statistics_routes import router as statistics_router
from app.modules.erp.stock_routes import router as stock_router
from app.platform.public_api import register_reconciliation_failure_consumer

definition = ModuleDefinition(
    code="erp",
    version="0.1.0",
    dependencies=("platform",),
    routers=(export_router, router, stock_router, purchase_router, purchase_stock_router, sale_router, sale_stock_router, finance_router, finance_document_router, audit_router, attachment_router, statistics_router, reconciliation_router),
    api_prefix="/api/v1/erp",
    permission_prefix="erp",
    migration=MigrationSpec(
        namespace="erp",
        schema="erp",
        owned_tables=(
            "product_unit",
            "product_category",
            "product",
            "warehouse",
            "warehouse_user_grant",
            "supplier",
            "customer",
            "document_sequence",
            "document_action_log",
            "command_receipt",
            "document_attachment",
            "erp_setting",
            "reconciliation_run",
            "settlement_account",
            "finance_payment",
            "finance_payment_item",
            "finance_receipt",
            "finance_receipt_item",
            "purchase_order",
            "purchase_order_item",
            "purchase_in",
            "purchase_in_item",
            "purchase_return",
            "purchase_return_item",
            "sale_order",
            "sale_order_item",
            "sale_out",
            "sale_out_item",
            "sale_return",
            "sale_return_item",
            "stock_balance",
            "stock_ledger",
            "stock_in",
            "stock_in_item",
            "stock_out",
            "stock_out_item",
            "stock_move",
            "stock_move_item",
            "stock_check",
            "stock_check_item",
        ),
    ),
    event_publishers=(
        EventContract("erp.purchase_order.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.purchase_order.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.purchase_in.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.purchase_in.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.purchase_return.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.purchase_return.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.sale_order.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.sale_order.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.sale_out.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.sale_out.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.sale_return.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.sale_return.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.stock_in.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.stock_in.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.stock_out.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.stock_out.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.stock_move.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.stock_move.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.stock_check.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.stock_check.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.payment.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.payment.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.receipt.approved", 1, allow_zero_subscribers=True),
        EventContract("erp.receipt.reversed", 1, allow_zero_subscribers=True),
        EventContract("erp.stock.changed", 1, allow_zero_subscribers=True),
        EventContract("erp.reconciliation.failed", 1),
    ),
    schedules=("erp.reconciliation.daily", "erp.command_receipt.cleanup"),
    schedule_handlers=(
        ScheduleHandler(
            code="erp.reconciliation.daily",
            interval_seconds=24 * 60 * 60,
            handler=run_daily_reconciliation,
        ),
        ScheduleHandler(
            code="erp.command_receipt.cleanup",
            interval_seconds=60 * 60,
            handler=cleanup_completed_command_receipts,
        ),
    ),
    reference_guards=(
        ReferenceGuardSpec("file", count_file_references),
        ReferenceGuardSpec("user", count_user_references),
    ),
    lifecycle=LifecycleHooks(
        register_event_handlers=register_reconciliation_failure_consumer,
    ),
    menus=(
        "erp:product-unit:list",
        "erp:product-unit:create",
        "erp:product-unit:update",
        "erp:product-unit:delete",
        "erp:product-unit:export",
        "erp:product-category:list",
        "erp:product-category:create",
        "erp:product-category:update",
        "erp:product-category:delete",
        "erp:product-category:export",
        "erp:product:list",
        "erp:product:create",
        "erp:product:update",
        "erp:product:delete",
        "erp:product:export",
        "erp:warehouse:list",
        "erp:warehouse:create",
        "erp:warehouse:update",
        "erp:warehouse:delete",
        "erp:warehouse:export",
        "erp:warehouse:assign",
        "erp:supplier:list",
        "erp:supplier:create",
        "erp:supplier:update",
        "erp:supplier:delete",
        "erp:supplier:export",
        "erp:customer:list",
        "erp:customer:create",
        "erp:customer:update",
        "erp:customer:delete",
        "erp:customer:export",
        "erp:account:list",
        "erp:account:create",
        "erp:account:update",
        "erp:account:delete",
        "erp:account:export",
        "erp:finance-sensitive:read",
        "erp:audit:list",
        "erp:attachment:list",
        "erp:attachment:create",
        "erp:attachment:delete",
        "erp:finance-payment:list",
        "erp:finance-payment:create",
        "erp:finance-payment:update",
        "erp:finance-payment:delete",
        "erp:finance-payment:approve",
        "erp:finance-payment:reverse",
        "erp:finance-payment:export",
        "erp:finance-receipt:list",
        "erp:finance-receipt:create",
        "erp:finance-receipt:update",
        "erp:finance-receipt:delete",
        "erp:finance-receipt:approve",
        "erp:finance-receipt:reverse",
        "erp:finance-receipt:export",
        "erp:purchase-order:list",
        "erp:purchase-order:create",
        "erp:purchase-order:update",
        "erp:purchase-order:delete",
        "erp:purchase-order:approve",
        "erp:purchase-order:reverse",
        "erp:purchase-order:export",
        "erp:purchase-in:list",
        "erp:purchase-in:create",
        "erp:purchase-in:update",
        "erp:purchase-in:delete",
        "erp:purchase-in:approve",
        "erp:purchase-in:reverse",
        "erp:purchase-in:export",
        "erp:purchase-return:list",
        "erp:purchase-return:create",
        "erp:purchase-return:update",
        "erp:purchase-return:delete",
        "erp:purchase-return:approve",
        "erp:purchase-return:reverse",
        "erp:purchase-return:export",
        "erp:sale-order:list",
        "erp:sale-order:create",
        "erp:sale-order:update",
        "erp:sale-order:delete",
        "erp:sale-order:approve",
        "erp:sale-order:reverse",
        "erp:sale-order:export",
        "erp:sale-out:list",
        "erp:sale-out:create",
        "erp:sale-out:update",
        "erp:sale-out:delete",
        "erp:sale-out:approve",
        "erp:sale-out:reverse",
        "erp:sale-out:export",
        "erp:sale-return:list",
        "erp:sale-return:create",
        "erp:sale-return:update",
        "erp:sale-return:delete",
        "erp:sale-return:approve",
        "erp:sale-return:reverse",
        "erp:sale-return:export",
        "erp:stock:list",
        "erp:stock:export",
        "erp:stock-record:list",
        "erp:stock-record:export",
        "erp:statistics:query",
        "erp:reconciliation:read",
        "erp:reconciliation:execute",
        "erp:stock-in:list",
        "erp:stock-in:create",
        "erp:stock-in:update",
        "erp:stock-in:delete",
        "erp:stock-in:approve",
        "erp:stock-in:reverse",
        "erp:stock-in:export",
        "erp:stock-out:list",
        "erp:stock-out:create",
        "erp:stock-out:update",
        "erp:stock-out:delete",
        "erp:stock-out:approve",
        "erp:stock-out:reverse",
        "erp:stock-out:export",
        "erp:stock-move:list",
        "erp:stock-move:create",
        "erp:stock-move:update",
        "erp:stock-move:delete",
        "erp:stock-move:approve",
        "erp:stock-move:reverse",
        "erp:stock-move:export",
        "erp:stock-check:list",
        "erp:stock-check:create",
        "erp:stock-check:update",
        "erp:stock-check:delete",
        "erp:stock-check:approve",
        "erp:stock-check:reverse",
        "erp:stock-check:export",
    ),
)
