from app.api.routes import (
    dashboard,
    departments,
    dictionaries,
    login,
    menus,
    modules,
    notices,
    oauth2,
    permissions,
    posts,
    roles,
    site_messages,
    social,
    tenants,
    users,
    utils,
)
from app.api.routes import settings as system_settings
from app.modules.contracts import EventContract, MigrationSpec, ModuleDefinition
from app.platform.infra import files_router, logs_router, mail_router, sms_router

definition = ModuleDefinition(
    code="platform",
    version="1.0.0",
    dependencies=(),
    routers=(
        login.router,
        dashboard.router,
        users.router,
        utils.router,
        logs_router.router,
        roles.router,
        menus.router,
        notices.router,
        permissions.router,
        posts.router,
        departments.router,
        dictionaries.router,
        system_settings.router,
        files_router.router,
        sms_router.router,
        mail_router.router,
        site_messages.router,
        oauth2.router,
        social.router,
        tenants.router,
        modules.router,
    ),
    api_prefix="/api/v1/platform",
    permission_prefix="platform",
    migration=MigrationSpec(namespace="platform", schema="public"),
    event_publishers=(
        EventContract("platform.module.observed_state.changed", 1, True),
        EventContract("platform.department.archived", 1, True),
        EventContract("platform.post.archived", 1, True),
        EventContract("platform.tenant.archived", 1, True),
        EventContract("platform.user.archived", 1, True),
        EventContract("platform.user.anonymized", 1, True),
    ),
    workers=("outbox-dispatch",),
)
